# Metadata
title: Talisman
description: >
  Straightforward fuzzy matching, information retrieval and NLP building blocks for JavaScript.
baseurl: /talisman
url: https://github.com/Yomguithereal/talisman

# Configuration
highlighter: rouge
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - webpack.config.js
